// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createUnsupportedSupabaseClient = (): SupabaseClient<Database> => {
  const errorResponse = async () => ({ data: null, error: { message: 'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.' } });
  const auth = {
    signInWithPassword: async () => ({ data: null, error: { message: 'Supabase is not configured.' } }),
    signOut: async () => ({ error: { message: 'Supabase is not configured.' } }),
    getSession: async () => ({ data: { session: null } }),
    getUser: async () => ({ data: { user: null }, error: { message: 'Supabase is not configured.' } }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  } as any;

  const from = () => ({
    select: errorResponse,
    maybeSingle: errorResponse,
    insert: errorResponse,
    upsert: errorResponse,
    delete: errorResponse,
    update: errorResponse,
  } as any);

  const storage = {
    from: () => ({
      upload: errorResponse,
      download: errorResponse,
      list: errorResponse,
      remove: errorResponse,
    }),
  } as any;

  return {
    auth,
    from,
    storage,
  } as unknown as SupabaseClient<Database>;
};

export const supabase = SUPABASE_CONFIGURED
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createUnsupportedSupabaseClient();